.PHONY: clean All

All:
	@echo "----------Building project:[ 45-Declaring-and-Initializing-Variables - Debug ]----------"
	@cd "45-Declaring-and-Initializing-Variables" && "$(MAKE)" -f  "45-Declaring-and-Initializing-Variables.mk"
clean:
	@echo "----------Cleaning project:[ 45-Declaring-and-Initializing-Variables - Debug ]----------"
	@cd "45-Declaring-and-Initializing-Variables" && "$(MAKE)" -f  "45-Declaring-and-Initializing-Variables.mk" clean
